image: dariksde/gcc-freifunkks:latest

# sadly gitlabci is missing a build matrix :(
ar71xx-generic:
  stage: build
  script:
    - make GLUON_TARGET=ar71xx-generic
  artifacts:
    paths:
      - gluon-build/output

ar71xx-tiny:
  stage: build
  script:
    - make GLUON_TARGET=ar71xx-tiny
  artifacts:
    paths:
      - gluon-build/output

ar71xx-nand:
  stage: build
  script:
    - make GLUON_TARGET=ar71xx-nand
  artifacts:
    paths:
      - gluon-build/output

mpc85xx-generic:
  stage: build
  script:
    - make GLUON_TARGET=mpc85xx-generic
  artifacts:
    paths:
      - gluon-build/output

x86-64:
  stage: build
  script:
    - make GLUON_TARGET=x86-64
  artifacts:
    paths:
      - gluon-build/output

x86-generic:
  stage: build
  script:
    - make GLUON_TARGET=x86-generic
  artifacts:
    paths:
      - gluon-build/output
